version: '3'
services:
    nvim:
        build: .
        image: nvim
        volumes:
            - ${PWD}:/share/nvim/
        working_dir: /share/nvim/
        environment:
            USER_ID: ${UID:-0}
            GROUP_ID: ${GID:-0}
        tty: true
